# Generated by Django 2.1.2 on 2018-11-20 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('splashads', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Nas',
        ),
        migrations.DeleteModel(
            name='Radacct',
        ),
        migrations.DeleteModel(
            name='Radcheck',
        ),
        migrations.DeleteModel(
            name='Radgroupcheck',
        ),
        migrations.DeleteModel(
            name='Radgroupreply',
        ),
        migrations.DeleteModel(
            name='Radpostauth',
        ),
        migrations.DeleteModel(
            name='Radreply',
        ),
        migrations.DeleteModel(
            name='Radusergroup',
        ),
    ]
