# Generated by Django 2.1.2 on 2018-12-03 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0018_auto_20181106_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='click',
            name='venue',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Venue'),
        ),
        migrations.AddField(
            model_name='impression',
            name='venue',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Venue'),
        ),
    ]
