# Generated by Django 2.1.2 on 2018-12-05 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0019_auto_20181203_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='impression',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Url'),
        ),
    ]
