# Generated by Django 2.1.2 on 2018-12-18 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0020_impression_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='click',
            name='venue',
        ),
    ]
